server.port : ${random.int[10000,11000]}
health : OK

endpoints :
  health :
    sensitive : false

banner.location : classpath:banner.txt

spring:
  application:
    name: Camel Application
  boot:
    admin:
        url: http://localhost:21000
  main :
    sources : ske.camel.springboot.CamelApplication

info :
   id : camel-application
   version : @project.version@
   build :
      artifact : @project.artifactId@
      name : @project.name@
      description : @project.description@
      version : @project.version@

app : ${spring.application.name}