server.port : ${random.int[10000,11000]}
health : OK

banner.location : classpath:banner.txt

spring:
  application:
    name: Camel Application
  boot:
    admin:
        url: http://localhost:21000
  main :
    sources : ske.camel.springboot.CamelApplication

endpoints :
    health :
        sensitive : false
    logfile :
      enabled : true
      sensitive : false

info :
   id : camel-application
   version : @project.version@
   stage : test
   build :
      artifact : @project.artifactId@
      name : @project.name@
      description : @project.description@
      version : @project.version@

app : ${spring.application.name}

logging :
  file : app.log